# Generated by Django 4.2.30 on 2026-06-19 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('jam_keluar', models.TimeField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ['-tanggal', '-jam_masuk'],
                'unique_together': {('karyawan', 'tanggal')},
            },
        ),
    ]
