# Generated by Django 4.2.30 on 2026-06-21 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_email_alter_employee_jabatan_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='jam_keluar',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-out Time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-in Time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
    ]
